### ISSUE TITLE
Can't find karma.sh

### ISSUE THREAD

**Issue by ptsefton** [lawlesst/vivo-vagrant#28]
I followed the instructions here and got VIVO running but the Karma script does not seem to be there, so this fails:

    sudo /home/vagrant/provision/karma.sh install

**Comment by lawlesst** [comment]
Hi. Good to hear VIVO is running. Is there any info printed to the console after `karma.sh` is run? The script is present in the repository so this is a bit odd.

Alternatively, you could [download](https://github.com/lawlesst/vivo-vagrant/blob/master/provision/karma.sh) separately and run it.

**Comment by lawlesst** [comment]
Believe this is fixed now. See #30. 

If you don't want to re-provision your box. The karma script just needs to be executable. Run:

`chmod +x /home/vagrant/provision/karma.sh`
